### ISSUE TITLE
Funding period selection

### ISSUE THREAD

**Issue by akariv** [openspending/subsidystories.eu#34]
- Remove underline from the selector element
- The title below the sum does not update to reflect the changes in the funding period

**Comment by michaeljokf** [comment]
I assume the filter works on the field "funding_period" in the data right? 
I found an issue for the Netherlands, we only have data from 2007-2013. However, when selecting 2014-2020 the same data is still displayed. Since there is no NL data with funding_period 2014-2020, something like N/A should be displayed instead.
