### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by akariv** [openspending/subsidystories.eu#8]
The current website is really not designed, we want to:
a. fix any usability problems (e.g. from too small visualisations etc.)
b. fix any aesthetic issues (which I will need your professional input on that)
c. apply a design that looks similar to http://labs.openspending.org/os-style-guide/ (doesn’t have to match exactly)

@annafralberts @DianaMPG if you have any other design suggestions please share as comments here.

**Comment by DianaMPG** [comment]
This issue relates to #191

@akariv @annafralberts @gocemitevski 
I would like to follow @akariv suggestion of greying out those EU countries on the graphical map of which we haven't acquired yet the data, but leave the EU map in one piece. 

Also, I would suggest a drop down option ("Search by country") with all the available countries rather than a written out list with the country names on the right-hand side (unless this has been done for the reason of visual impairment since screen readers can't read drop-downs).

**Comment by gocemitevski** [comment]
@akariv 
Here is an early work-in-progress update with the grayed out countries. I have excluded Russia though. The geoJSON file with the country coordinates is also stripped of all the non-European countries.

![screen shot 2016-12-22 at 16 35 24-fullpage](https://cloud.githubusercontent.com/assets/359855/21430761/d2dd86fe-c864-11e6-8479-bb4bb2929ab7.png)

> Also, I would suggest a drop down option ("Search by country") with all the available countries rather than a written out list with the country names on the right-hand side (unless this has been done for the reason of visual impairment since screen readers can't read drop-downs).

@DianaMPG 
Adding an additional control seems like a better idea, rather than removing the list altogether.

cc @pwalsh @kravets-levko

**Comment by DianaMPG** [comment]
@gocemitevski it works very well with greying out, thank you. 
Is there the possibility that we could move Island a bit closer to the rest? 
Currently, Island is lurking behind the "Github" :-)

**Comment by gocemitevski** [comment]
@DianaMPG yes, I agree. Works better with the grayed out countries.

Maybe having the menu in vertical order -- like shown below -- can solve the issue with Island. I'm still experimenting, so I will post more samples soon.

![screen shot 2016-12-23 at 10 00 48-fullpage](https://cloud.githubusercontent.com/assets/359855/21450382/c4d84f20-c8f6-11e6-8af1-e19f5e8b13ee.png)

**Comment by DianaMPG** [comment]
@gocemitevski great. 

I have some more suggestions for the design:
- Russia: since we have now the greying option, could we put Russia back in, greyed out?
- I actually like the horizontal order. We for sure can push Iceland a little, we can be off the track geographically speaking. But let's see how it looks.
- As for the details side: 
http://subsidystories.eu/country.html?country=DE
I would prefer the information not being displayed on four squares but displayed without any partition. 
More like a country fact sheet, a bit like this: 
http://www.africaneconomicoutlook.org/en/africahumandevreport2016

The partition might be confusing since one of the squares could remain empty - for no obvious reason. 
So lining up the information one after another makes more sense:

<country name>
< amount>
<time spawn>
< top recipients>
<tree map visualization>

- Technical (bottom). 
Would it be possible to to offer the option "Get the raw data spreadsheet" also on the details page?

**Comment by gocemitevski** [comment]
@akariv thanks.

> I actually like the horizontal order. We for sure can push Iceland a little, we can be off the track geographically speaking. But let's see how it looks.

Now that we have Russia back, I think the vertical order makes quite more sense.

![screen shot 2016-12-23 at 14 32 08-fullpage](https://cloud.githubusercontent.com/assets/359855/21454946/c294acb0-c91c-11e6-8ff5-9a46ddf48601.png)

>  I would prefer the information not being displayed on four squares but displayed without any partition.

I completely agree. The squares don't server their purpose, since the date we need to include in them is much more extensive.

**Comment by DianaMPG** [comment]
@gocemitevski thanks!

**Comment by gocemitevski** [comment]
@akariv @DianaMPG 

Here is how things might look if we have a dropdown as well.

![screen shot 2016-12-23 at 15 51 17-fullpage](https://cloud.githubusercontent.com/assets/359855/21456428/512313e4-c928-11e6-8285-902444830ccc.png)

**Comment by DianaMPG** [comment]
@gocemitevski @akariv I like that very much, elegantly positioned, in my opinion. 

@akariv @annafralberts

**Comment by gocemitevski** [comment]
@akariv, @DianaMPG, @annafralberts  

the recent updates are now available on http://subsidystories.eu/, thanks to @kravets-levko.

**Comment by DianaMPG** [comment]
@gocemitevski @kravets-levko thanks so much.

**Comment by gocemitevski** [comment]
@akariv @DianaMPG @annafralberts 

http://subsidystories.eu/ has been updated to the most recent version. This time the updates are mostly related to polishing, usability and responsive design.

https://github.com/openspending/subsidystories.eu/commits/master

The download button is yet to be added.

cc @kravets-levko

**Comment by DianaMPG** [comment]
@gocemitevski @akariv @kravets-levko @annafralberts 
Please find the consolidated design / functionality spec here
https://docs.google.com/document/d/1VdKnM8XQxPrJdTXDoOsrU3GXMXqxxbYxWWkm2csyyQ4/edit

**Comment by gocemitevski** [comment]
@akariv @annafralberts @DianaMPG @kravets-levko 

Here is another possible look for the header with the introductory text and repositioned menu.

![screen shot 2016-12-29 at 12 38 39-fullpage](https://cloud.githubusercontent.com/assets/359855/21543174/1a62be5e-cdc4-11e6-90ab-415a14dfb27b.png)

**Comment by gocemitevski** [comment]
@akariv @DianaMPG @annafralberts 

More changes deployed on http://subsidystories.eu/. Most of the changes are within the map area and the country page data.

cc @kravets-levko

**Comment by DianaMPG** [comment]
@gocemitevski it looks great, elegant and sophisticated! I like it very much, both main page/map area and country page. 

Only one slight change: 
Text: Explore the available data. Click on the map, choose from the dropdown list or the country list on the right-hand side. = same font than intro text but with the same spacing. Than we are good on this part. 

As to clicking on the map as suggested in the spec: let's refrain from it for now, needs more thinking. 
That said, we would need to get rid of the "Click on the map" text bit. 

Still waiting for @annafralberts feedback on open spec comments.
